services:
  kiwix:
    image: ghcr.io/kiwix/kiwix-serve:latest
    container_name: offgrid-tools-kiwix
    ports:
      - "8000:8080"
    volumes:
      - ./zim/data:/data:ro
    command: "*.zim"
    restart: unless-stopped
    networks:
      - offgrid
    environment:
      - PORT=8080

  ollama:
    image: ollama/ollama:latest
    container_name: offgrid-tools-ollama
    expose:
      - 11434
    volumes:
      - ./ollama/data:/root/.ollama
    restart: unless-stopped
    networks:
      - offgrid
    environment:
      - OLLAMA_HOST=0.0.0.0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: offgrid-tools-openwebui
    ports:
      - "8001:8080"
    volumes:
      - ./openwebui/data:/app/backend/data
    restart: unless-stopped
    networks:
      - offgrid
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - HF_HUB_OFFLINE=1
    depends_on:
      - ollama

  ollama-chat-party:
    image: psyb0t/ollama-chat-party:latest
    container_name: offgrid-tools-ollama-chat-party
    tty: true
    ports:
      - "8002:8000"
    volumes:
      - ./ollama-chat-party/data:/documents
    restart: unless-stopped
    networks:
      - offgrid
    environment:
      - OLLAMA_CHAT_PARTY_WEB_UI_PASSWORD=offgrid123
    command:
      [
        "--listen",
        "0.0.0.0:8000",
        "--rag-dir",
        "/documents",
        "--ollama-url",
        "http://ollama:11434",
      ]
    depends_on:
      - ollama

  inspircd:
    image: inspircd/inspircd-docker:latest
    container_name: offgrid-tools-inspircd
    user: "1000:1000"
    expose:
      - 6667
    volumes:
      - ./inspircd/conf:/inspircd/conf
      - ./inspircd/logs:/inspircd/logs
    restart: unless-stopped
    networks:
      - offgrid

  thelounge:
    image: thelounge/thelounge:latest
    container_name: offgrid-tools-thelounge
    ports:
      - "8003:9000"
    volumes:
      - ./thelounge:/var/opt/thelounge
    restart: unless-stopped
    networks:
      - offgrid
    environment:
      - THELOUNGE_HOME=/var/opt/thelounge
    depends_on:
      - inspircd

  icecast:
    image: libretime/icecast:latest
    container_name: offgrid-tools-icecast
    ports:
      - "8004:8000"
    restart: unless-stopped
    networks:
      - offgrid
    environment:
      - ICECAST_SOURCE_PASSWORD=offgrid123
      - ICECAST_ADMIN_PASSWORD=offgrid123
      - ICECAST_RELAY_PASSWORD=offgrid123
      - ICECAST_PASSWORD=offgrid123

  file-server:
    image: nginx:alpine
    container_name: offgrid-tools-file-server
    ports:
      - "8005:8002"
    volumes:
      - ./file-server/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./file-server/entrypoint.sh:/entrypoint.sh:ro
      - ./apps/android/apk/data:/var/www/html/apk:ro
      - ./apps/linux/deb/data:/var/www/html/deb:ro
      - ./apps/iso/data:/var/www/html/iso:ro
      - ./docker-images:/var/www/html/docker-images:ro
      - ./zim/data:/var/www/html/zim:ro
      - ./file-server/other-files:/var/www/html/other-files
    environment:
      - FILE_SERVER_AUTH=offgrid:offgrid123
    entrypoint: ["/entrypoint.sh"]
    restart: unless-stopped
    networks:
      - offgrid

networks:
  offgrid:
    driver: bridge
